// flow-typed signature: 4c4e42925c581b2590b2e8fb517a73ae
// flow-typed version: <<STUB>>/font-awesome_v^4.7.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome' {
  declare module.exports: any;
}
